name: Build and publish latest Docker image

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
     - main
    paths:
     - Dockerfile.alpine
     - Dockerfile.bullseye
     - entrypoint.sh
     - .github/workflows/latest.yml

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/boringtun

jobs:
  build-and-push-bullseye:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Bullseye version
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.bullseye
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:bullseye
          push: true

  build-and-push-alpine:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Alpine version
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.alpine
          tags: ${{ env.IMAGE }}:alpine
          push: true
